/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figuras;

/**
 *
 * @author Usuario
 */
public class VentanaFiguras extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFiguras
     */
    public VentanaFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        comboFiguras = new javax.swing.JComboBox<>();
        btnSalirPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("CALCULO DE AREA Y PERIMETRO");

        lblSubTitulo.setText("ESCOJA LA FIGURA");

        comboFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadrado", "Circulo", "Rectangulo", "Triangulo" }));
        comboFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFigurasActionPerformed(evt);
            }
        });

        btnSalirPrincipal.setText("SALIR");
        btnSalirPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lblSubTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalirPrincipal)
                            .addComponent(comboFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblSubTitulo)
                .addGap(18, 18, 18)
                .addComponent(comboFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(btnSalirPrincipal)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFigurasActionPerformed
        String opcion = comboFiguras.getSelectedItem().toString();
        switch(opcion){
            case "Cuadrado":
                System.out.println("cuadrado");
                dispose();
                VentanaCuadrado Vcuadrado = new VentanaCuadrado();
                Vcuadrado.setVisible(true);
                
                break;
                
            case "Circulo":
                System.out.println("Circulo");
                dispose();
                  VentanaCirculo Vcirculo = new VentanaCirculo();
                Vcirculo.setVisible(true);
                break;
                
            case "Rectangulo":
                System.out.println("Rectangulo");
                dispose();
                  VentanaRectangulo Vrectangulo = new VentanaRectangulo();
                Vrectangulo.setVisible(true);
                break;
                
            case "Triangulo":
                
                System.out.println("Tringulo");
                dispose();
                VentanaTriangulo Vtriangulo = new VentanaTriangulo();
                Vtriangulo.setVisible(true);
                break;
        }
    }//GEN-LAST:event_comboFigurasActionPerformed

    private void btnSalirPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirPrincipalActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirPrincipal;
    private javax.swing.JComboBox<String> comboFiguras;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
